name: Build i915 for DSM epyc7002

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: [7.1, 7.2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download toolchain
        run: |
          env_tarball=ds.epyc7002-${{ matrix.version }}.env.txz
          wget https://global.synologydownload.com/download/ToolChain/toolkit/${{ matrix.version }}/epyc7002/$env_tarball
          mkdir toolchain
          tar xf $env_tarball -C toolchain

      - name: Download kernel source
        run: |
          dev_tarball=ds.epyc7002-${{ matrix.version }}.dev.txz
          wget https://global.synologydownload.com/download/ToolChain/toolkit/${{ matrix.version }}/epyc7002/$dev_tarball
          mkdir ksrc
          tar xf $dev_tarball -C ksrc

      - name: Build
        run: |
          export BACKPORT_DIR=$PWD
          export KLIB_BUILD=$PWD/ksrc/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-${{ matrix.version }}/build
          export CROSS_COMPILE=$PWD/toolchain/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-
          make defconfig-drm
          make -j$(nproc) modules_copy

      - name: Save Build Result
        uses: actions/upload-artifact@v3
        with:
          name: i915_dsm-${{ matrix.version }}_epyc7002
          path: out/modules/
